[DEN-315] OriginV3 Group Management Examples
Edgio/ec-sdk-go pull request #120
Opened 2022-10-25 17:12 UTC by wdawg33

1) Added OriginV3 group management examples
2) Refactored Platform enum default String() case to return platform with hyphen
3) Added StringWithoutHyphen method for convenience
4) Refactored previous usages of Platform.String() to PlatformWithoutString() to match previous default behavior

2022-10-28 16:36 UTC, stevenpaz requested changes

2022-10-28 16:36 UTC, stevenpaz commented on edgecast/ecutils/convert.go
> +			"unable to marshal get origin group response: %w", err)
I think this error message carried over from an origin specific usage

2022-10-28 16:36 UTC, stevenpaz commented on edgecast/ecutils/convert.go
> +// Please refer to the json unmashall documentation for additional information
Couple of typos: "If dest" and "unmashall"

2022-11-05 01:40 UTC, ssaluja4 approved these changes

2022-11-07 18:57 UTC, stevenpaz approved these changes

2022-11-08 01:09 UTC, merged